# Generated by Django 4.0.2 on 2022-02-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('contributor', 'contributor'), ('viewer', 'viewer')], default='viewer', max_length=11),
        ),
    ]
