# Generated by Django 4.0.2 on 2022-03-08 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0019_alter_document_file'),
        ('account', '0007_profile_employee_alter_profile_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='employee',
            new_name='employee_num',
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('company', 'employee_num')},
        ),
    ]
