# Generated by Django 3.2.12 on 2022-02-12 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.category', verbose_name='document category'),
        ),
        migrations.AlterField(
            model_name='document',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.product', verbose_name='insurance product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=60, verbose_name='name of insurance product'),
        ),
    ]
