# Generated by Django 4.0.2 on 2022-02-24 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_remove_category_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='company',
        ),
    ]
