# Generated by Django 4.0.2 on 2022-02-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_remove_document_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='code',
            field=models.CharField(default='aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', max_length=32),
            preserve_default=False,
        ),
    ]
