# Generated by Django 4.0.2 on 2022-02-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_company_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='full_name',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
