# Generated by Django 4.0.2 on 2022-02-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0009_company_full_name_alter_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
