# Generated by Django 4.0.2 on 2022-02-27 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0012_product_company_product_company_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='document.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='company_category_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(help_text='E.g. TERM02', max_length=20, verbose_name='cash flow model'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='E.g. Term Life Insurance', max_length=60, verbose_name='name of insurance product'),
        ),
    ]
