# Generated by Django 4.0.2 on 2022-02-27 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0013_category_company_category_company_category_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='document',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='document',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='document.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='E.g. Terms and conditions or Technical description', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('company', 'product', 'category', 'validity_start')},
        ),
    ]
