# Generated by Django 4.0.2 on 2022-02-28 18:52

from django.db import migrations, models
import document.models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0014_alter_document_unique_together_document_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=document.models.document_path),
        ),
    ]
