# Generated by Django 4.0.2 on 2022-02-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0015_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='company_document_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
