# Generated by Django 4.0.2 on 2022-03-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0017_alter_category_unique_together_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['company', 'company_category_id'], name='document_ca_company_600325_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='document_co_name_d65ce3_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['company', 'company_document_id'], name='document_do_company_6d3f81_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'company_product_id'], name='document_pr_company_ef7de1_idx'),
        ),
    ]
