# Generated by Django 4.0.2 on 2022-03-08 06:11

from django.db import migrations, models
import document.models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0018_category_document_ca_company_600325_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=document.models.document_path, validators=[document.models.validate_file_extension]),
        ),
    ]
