# Generated by Django 4.0.2 on 2022-03-08 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0019_alter_document_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
    ]
