# Generated by Django 4.0.2 on 2022-03-23 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0020_alter_category_options_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-id']},
        ),
    ]
