# Generated by Django 3.2.13 on 2022-07-06 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0024_alter_document_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('company', 'category', 'validity_start')},
        ),
    ]
